### ISSUE TITLE
Handling command line arguments when using "CI run all" module

### ISSUE THREAD

**Issue by filfreire** [CyberGRX/questions-three#18]
If a user decides tries to do the following:
```
python -m questions_three.ci.run_all my_checks --foo foo --bar bar
```

the [sys.argv](https://docs.python.org/3/library/sys.html#sys.argv) will ignore the run arguments, and inside each check suite covered by `my_checks`, sys.argv only returns the name of the check .py script that is being executed.

I think in this case, the user has no easy way of getting those command line arguments (that are used, say, when we run a suite individually, e.g. `python my_checks/individual_suite.py --foo foo --bar bar`).

I'm not entirely sure if this is expected or default to the way python works ([see this link](https://stackoverflow.com/a/50821362), where `-m` implies "run library module as a script (terminates option list)")
Any ideas on how this could be tackled so we can still fetch the command line arguments?

cc @mikeduskis @BrennanAyers @ToddBradley

**Comment by ToddBradley** [comment]
From what I understand, I think this is "default to the way python works". If I were in your shoes, and wanted to pass other arguments on the command line, I would write my own wrapper script that gathers the command line arguments (`--foo foo --bar bar`) and handles them however you want while also executing the `run_all` code with `my_checks` as the input argument.

Or, alternatively, have foo and bar be set as environment variables; that feels a little kludgey but might be simpler to implement, depending on what you want foo and bar to do.

**Comment by filfreire** [comment]
Thank you @ToddBradley. Worked an alternative in such a way that on the setup stage of the suite, I check either for environment variable named `RUN_ARGS`, or for the args themselves, and I use either approach depending on if I run with the module or not, respectively. Closing this issue 👍
